# These are supported funding model platforms

github: [mrdoob, HumanInteractive, donmccurdy]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a Single Open Collective username
